def nock():
    no = int (input("enter a number"))
    if no ==0:
        print("the number is zero")
    elif no>=1:
        print("this is a positive") 
    elif no<=1:
        print("this is negative no")
nock()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
